#!/bin/python

import math
import os
import random
import re
import sys

# Complete the factorial function below.
N = int(raw_input())

def factorial(x):
    if x == 0:
        return 1
    return x * factorial(x - 1)

print factorial(N)


